jobs:
  keep_file_updated:
    runs-on: ubuntu-latest
    name: Keep file updated
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v2

    - name: Update PhoneNumberMetadata
      id: update_PhoneNumberMetadata
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml
        file_in_repo: data/telephone_number_data_file.xml

    - name: Update geocoding
      run: rm -rf -v data/geocoding && wget https://github.com/google/libphonenumber/tree/master/resources/geocoding -O data/geocoding && git add data/geocoding && git commit -m "Update" && git push

    # - uses: suisei-cn/actions-download-file@v1.0.1
    #   id: Update_geocoding  # Remember to give an ID if you need the output filename
    #   name: Update geocodinge
    #   with:
    #     url: https://github.com/google/libphonenumber/tree/master/resources/geocoding
    #     target: data/geocoding

    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v3.6.0
    #   with:
    #     committer: ankit-tangoe <ankit.pandey@tangoe.com>
    #     author: ankit.pandey@tangoe.com
    #     commit-message: "feat(sound): Add qwerty"
    #     title: "feat(sound): Add 234"
    #     body: |
    #       This is an automated sound addition PR. Netlify preview should be available soon, and a preview link should be shown.
    #       <sub>Having problems? Check your [workflow](https://github.com/suisei-cn/sbtn-assets/blob/master/.github/workflows/auto_pr.yml).</sub>
    #     branch: sound/new
    #     branch-suffix: "random"
    #     labels: new-sound


    # - name: Update resources
    #   uses: test-room-7/action-update-file@v1
    #   with:
    #       # Include all JS files from the `dist` directory
    #       file-path: data/*
    #       commit-msg: Update resources
    #       github-token: ${{ secrets.GITHUB_TOKEN }} 
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Get latest data'
        # Default value if no value is explicitly provided
        default: 'fetch'
        # Input has to be provided for the workflow to run
        required: true

# name:  Copy content to telephone

# jobs:
#   copy-file:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: geocoding
#       uses: dmnemec/copy_file_to_another_repo_action@main
#       env:
#         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#       with:
#         source_repo: 'google/libphonenumber'
#         source_branch: 'master'
#         source_folder: 'resources/geocoding' # Folder to copy
#         destination_rile: 'data/' # Target file
#         user_email: 'ankit.pandey@tangoe.com'
#         user_name: 'ankit-tangoe'
#         commit_message: "AUTO: Copying posts from libphone_number's to telephone_number's repo"
#         git_server: 'github.com'

#     - name: Push publications
#       uses: dmnemec/copy_file_to_another_repo_action@main
#       env:
#         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#       with:
#         source_file: 'content/publication/' # Folder to copy
#         destination_repo: 'RealityBending/RealityBending.github.io' # Target repo
#         destination_folder: 'content/' # Folder where to copy it
#         user_email: 'dom.makowski@gmail.com'
#         user_name: 'DominiqueMakowski'
#         commit_message: "AUTO: Copying publications from Dom's to REBEL's website"
#         git_server: 'github.com'

#     - name: Publish to RubyGems
#       run: |
#         mkdir -p $HOME/.gem
#         touch $HOME/.gem/credentials
#         chmod 0600 $HOME/.gem/credentials
#         printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
#         gem build *.gemspec
#         gem push *.gem
#       env:
#         GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
